### ISSUE TITLE
[Suggestion] A way to move the MacroKey Keybindings button

### ISSUE THREAD

**Issue by TheRandomLabs** [Matts/MacroKey#2]
It overlaps with buttons added by several other mods. It would also be nice if you backported it to 1.10.2. :)

**Comment by Matts** [comment]
You can customize all buttons, even the activation button.
It's available for 1.10.2 just don't have the build source on here.
https://minecraft.curseforge.com/projects/macrokey-keybinding

**Comment by TheRandomLabs** [comment]
By backport, I meant backporting the feature. Also, where in the config can I find this?

**Comment by Matts** [comment]
What feature do you want backported? I haven't changed the codebase since updating to 1.10.2
You can find it in the ingame controls tab

**Comment by TheRandomLabs** [comment]
I meant the "changing the position" feature. I'll have a look.

**Comment by zurbo** [comment]
I think @TheRandomLabs made a reference to something like that: [Menu with overlaping buttons](https://i.imgur.com/l1F0aJf.png)
The buttons underneath yours come from the mod "WorldDownloader" on liteloader.
I changed the position of the layer button by rebuilding the mod but it's quite frustrating :)

**Comment by Matts** [comment]
Will make this a config option during #14, will be something in the lines of _MacroKey Button Location: -1 = disabled, otherwise x,y,z_

**Comment by Matts** [comment]
The layer switcher now can be changed from its location through the ingame mod config UI

https://github.com/Matts/MacroKey/pull/29
