### ISSUE TITLE
Crash with loading game

### ISSUE THREAD

**Issue by SeanChengN** [Matts/MacroKey#47]
**Describe the bug**
Crash with loading game.

**To Reproduce**
Start game.

**Expected behaviour**
Need to fix crash.

**Screenshots**
Nope.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Minecraft Version: 1.12.2
 - MacroKey Version: 2.0.0.157
 - Release Type: RELEASE

**Downloaded From**
CurseForge.com

**Additional context**
Crash report: https://pastebin.com/0ZHTPzF8

**Comment by Matts** [comment]
Hi Sean,

Can you post your bindings.json file found in config/macrokey

**Comment by SeanChengN** [comment]
```
# Configuration file

general {
    # What file should be used for saving the bindings and various other dynamic information (default: bindings.json)
    S:bindingFile=bindings.json

    # Customize the position that the button for switching layer should use, expected is {x, y, width, height} (default: -100, 128, 200, 20)
    I:buttonLayerSwitchSettings <
        -100
        128
        200
        20
     >

    # Customize the ID that is used when creating the button for switching layers (default: 823358142), (-1 = disabled)
    I:buttonLayerSwitcherId=823358142

    # Customize the ID that is used when calling the macro management GUI (default: 423458971)
    I:guiMacroManagementId=423458971

    # How many ticks need to pass for the repeatable command cooldown timer to expire (default: 20 ticks -> 1 second)
    I:repeatDelay=20
}
```

**Comment by SeanChengN** [comment]
{"version":2,"macros":[{"umid":"bec1a4fe-1e91-43d2-b403-cf892c2c1af5","keyCode":79,"repeat":false,"command":"/stackup reload","active":true},{"umid":"d663fec9-f266-465b-b4d3-485378bf154d","keyCode":80,"repeat":false,"command":"/gamemode 1","active":true},{"umid":"bfc11d84-e232-484f-9e41-c0ef218953b7","keyCode":81,"repeat":false,"command":"/gamemode 0","active":true}],"layers":[]}

**Comment by SeanChengN** [comment]
Oh, I have figured it out now.
If I remove the mod that command has been bound, MacroKey will crash.
Could u ignore the mod that was removed?

**Comment by Matts** [comment]
Thanks for your report,

I found why this happens, and it's completely my fault, You were a BETA user.

I have added a new feature without thinking of them, sorry my bad. This is not related to removed mods, but related to an invalid file syntax.

For future support of different kinds of commands (ex. programming), I've modified the command string. This string now has an additional required parameter (type), this makes it a json object. Seeing as your bindingsfile.json is small, you are better of removing it and relaunching minecraft to add the ones you need.

I've added an item on the project roadmap to add a script to convert bindingfile versions

If you have any questions, please don't hesitate to reopen the ticket.
