### ISSUE TITLE
Crashing while deleting new layer

### ISSUE THREAD

**Issue by PapiChase** [Matts/MacroKey#48]
Upon the action of trying to delete a layer, the game just out right crashes. Says it crashed while updating screen events. Hope it gets fixED!

**Comment by Matts** [comment]
Can you provide the crashlog, minecraft version and macrokey version

**Comment by ChaoticLogic** [comment]
I also experienced this issue. Here is my log:
https://paste.ee/p/KGe4F

**Comment by Matts** [comment]
Found the issue, this is because I am checking for the current layer when deleting, when this layer does not exist it will probably throw a nullpointer.

Temporary workaround: make sure you are not on the "master" layer when deleting layers. Rather be on any other layer.

**Comment by Matts** [comment]
Thanks @ChaoticLogic and @PapiChase for reporting this issue.
This will be solved in MacroKey 2.0.1
