### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by Nisutec** [Matts/MacroKey#5]
Hello,
On the download page was writen that is a version for 1.12 available.
But i dont find a download link for the version.

**Comment by Matts** [comment]
@Nisutec Where are you looking?

**Comment by Nisutec** [comment]
On Planet Minecraft

Now out for Minecraft 1.8, 1.8.8, 1.8.9, 1.9, 1.9.4, 1.10, 1.10.2, 1.11, 1.11.2 & 1.12 

https://www.planetminecraft.com/mod/forge-macrokey-19/

And on the Curse description 

https://mods.curse.com/mc-mods/minecraft/243479-macrokey-keybinding

**Comment by Matts** [comment]
Please click through to my download page on curse
https://mods.curse.com/mc-mods/minecraft/243479-macrokey-keybinding

**Comment by Nisutec** [comment]
Ok

**Comment by Nisutec** [comment]
I was on your page

**Comment by Nisutec** [comment]
No 1.12 download

**Comment by Nisutec** [comment]
oh i have found it thanks

**Comment by JannisX11** [comment]
The 1.12 version is not the highest version in the list, that's why the default download button still downloads the 1.11.2 version and people think that there is no 1.12 version yet. I guess you could fix that.
