### ISSUE TITLE
Required to press button twice

### ISSUE THREAD

**Issue by Matts** [Matts/MacroKey#51]
Macro's are only activated if you press the macro button twice.

**Comment by Matts** [comment]
It seems like I made a derp, macro's are executed on tick and if you release the button before the tick occurs then the macro will be removed from the "to run" list before it can run.

**Comment by Kiefy** [comment]
This is still a problem in 2.0.3. (MC 1.12.2)

In case there is a conflict, I added your mod to the Enigmatica 2: Expert Modpack on Twitch.
