### ISSUE TITLE
Feature: Client-side bindable commands

### ISSUE THREAD

**Issue by mchorse** [Matts/MacroKey#52]
**Is your feature request related to a problem? Please describe.**
Yes, MacroKey is by itself is a very awesome command mod, but at the moment there is no way to execute commands bind on the client side.

**Describe the solution you'd like**
I would like you (or me, I can PR) to add a feature that will allow executing client side and server side command execution. A check box or a button, for example to toggle between server side and client execution.

I see you have a comment in `StringCommand`, and you're probably aware of that. I could lend a hand, but with your design choices (i.e. `Macro` itself stores properties, meanwhile `CommandInterface` isn't aware of `Macro`'s properties), I'm not 100% sure how you would've wanted to implement it.

**Describe alternatives you've considered**
There is no alternatives really.

**Comment by Matts** [comment]
Already tested working with 1.17 & 1.16 :) (2.1.0)
