### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by BleuBleue** [Matts/MacroKey#6]
Hello, i'm very sorry for my very bad english, i'm FR player.

So i use Google translate for speak with you.

I recently noticed that if we put accent or special characters in the recorded mmaccro, after the game is restarted, the accents, symbols and the like are replaced with white squares with a "?" Where simply a?
I think this comes from the encoding of the text that is in UTF8 whereas it should be in "UTF8-BOM Free"

Thank you for reading me, and I apologize again for my very bad English

**Comment by Matts** [comment]
Will keep this in mind during the development of MacroKey 2.0.x, won't fix for 1.6.*

**Comment by Matts** [comment]
Hi, I am currently working on your ticket; and it should be solved now for MacroKey 2.0. 
Would it be possible for you to test this in Build 75 in Minecraft 1.12.x https://ci.mattsmeets.com/job/MacroKey/75/

If you have any other questions regarding this ticket, please do not hesitate to re-open it

Closing #6 until further response
