### ISSUE TITLE
unfinished language file

### ISSUE THREAD

**Issue by h3oCharles** [Matts/MacroKey#69]
**Describe the bug**
the language file is unfinished, you can notice most of the texts are in the debug names

**To Reproduce**
uuuh

**Expected behaviour**
a finished language file

**Screenshots**
do i have to...?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.8.9
 - MacroKey Version: 2.0.1 b187
 - Release Type: RELEASE

**Downloaded From**
CurseForge

**Additional context**
I attempted to add the missing language strings for English

`key.macrokey.category=MacroKey Keybinding`
`key.macrokey.management.desc=Macro Management`
`gui.manage.text.title=Manage Macros`
`gui.manage.text.macro.add=Add Macro`
`fragment.list.text.remove=X`
`gui.modify.text.save=Save Macro`
`gui.modify.text.command=Command`
`gui.modify.text.key=Key`
`gui.modify.text.repeat=Repeat`
`gui.modify.text.enable=Enabled`
`text.layer.display=Layer: %1$s`
`text.layer.master=Master`
`gui.manage.text.layer.edit=Edit Layers`
`gui.manage.layer.text.title=Manage Layers`
`gui.manage.text.layer.add=Add Layer`
`gui.modify.layer.text.save=Save Layer`

EDIT1:
After inspecting the mod jar file, there IS a language file, but it's called "en_us.lang", shouldn't it be "en_US.lang"?
also these three commands aren't effective, i can still see these strings in lower case:
`enabled=Enabled`
`disabled=Disabled`
`edit=Edit`

EDIT2: After extracting, renaming, and putting back the language file, the issue was solved

**Comment by mariya1129** [comment]
Could you please leave a link to the fixed file as when I try to zip mine with the correct language file, it gives me an error. If you could, leave your discord tag in the reply to this comment

**Comment by h3oCharles** [comment]
rename "en_us.json" to "en_US.json"
and yes, this is case sensitive

**Comment by mariya1129** [comment]
> rename "en_us.json" to "en_US.json"
> and yes, this is case sensitive

I already tried that and it didn't work, hence me asking for the file instead.

**Comment by h3oCharles** [comment]
try extracting "en_us.json" from the mod jar, then deleting the file from the archive, rename it to "en_US.json" and then insert it to the archive
