### ISSUE TITLE
No 1.16.5

### ISSUE THREAD

**Issue by btpv** [Matts/MacroKey#71]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Matts** [comment]
1.17.1 has been released. will see if i get to porting it back to 1.16

**Comment by Matts** [comment]
1.16.5 is out now https://www.curseforge.com/minecraft/mc-mods/macrokey-keybinding/files/3519353

**Comment by btpv** [comment]
tnx you only need to fix this
![image](https://user-images.githubusercontent.com/62651117/140725358-eb9c07d5-cbf7-413e-863f-db6a1a85b1e1.png)

**Comment by Matts** [comment]
Updated.
